---
# tasks file for ansible-role-demo-config
      # - name: hostname set
      #   hostname:
      #     name: "{{ newhostname | default('server.eos.com') }}"


      - name: Yum install HTTPD and Firewalld
        yum: 
          name: "{{ item }}"
          state: latest
        loop:
          - firewalld
          - httpd

      
      - name: Template index.html file
        template:
          src: index.j2
          dest: /var/www/html/index.html

      # - name: Firewalld - Enable HTTP
      #   firewalld: 
      #     port: "{{ item }}"
      #     state: enabled
      #     permanent: yes
      #   loop:
      #     - 80/tcp
      #   notify: 'Restart'




